_prefs: 
  saveCenter: true
_properties: {}
attribution: Washington Recreation and Conservation Office - 2014
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -128.34228515625
  - 43.12504316740127
  - 6
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 3
name: Washington Federal Lands
source: "mapbox:///smartmine.gcrtfbt9"
styles: 
  - federal_lands.mss
template: ''
