_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: Washington Public Lands
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -120.640869140625
  - 47.57652571374621
  - 6
description: Washington Public Lands Federal Lands
format: "png8:m=h"
interactivity_layer: washington_rco_publiclands_parcels
layers: null
maxzoom: 16
minzoom: 6
name: Washington Public Lands Federal Lands
source: "tmsource:///Users/blairdeaver/Documents/projects/rco/rco_publiclands_taxlots.tm2source"
styles: 
  - style.mss
template: |-
  <div style="text-align:center;">
  <strong>{{TAXID}}</strong>
  <strong>{{OWNER}}</strong>
  <strong>{{ACQYEAR}}</strong>
  <strong>{{OWNTYPE}}</strong>
  <strong>{{ACRES}}</strong>
  <strong>{{PLAND}}</strong>
  <strong>{{ACQCOST}}</strong>
  <strong>{{UNITNAME}}</strong>
  </div>