BootstrapVars = {} || BootstrapVars;

BootstrapVars.areaStats = [
	{
		abbrev: "DFW",
		agency: "Department of Fish and Wildlife",
		total_acres : 995329.78,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.izm5nrk9",
		visible: true,
		layerGroupName: "agency",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#FFEBCD'

	},
	{
		abbrev: "PARKS",
		agency: "Washington Parks Department",
		total_acres : 397973.62,
		total_cost: 1,
		total_revenue: 1,
		mapTarget: "smartmine.zypq4cxr",
		visible: true,
		layerGroupName: "agency",
		layerGroup: null,
		symbol: '#x21f4;',
		color: '#FFCC00'
	},
	{
		abbrev: "DNR",
		agency: "Department of Natural Resources",
		total_acres : 392340.89,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.to36usor",
		visible: true,
		layerGroupName: "agency",
		layerGroup: null,
		symbol: '#x214a;',
		color: '#428BCA'
	},
	{
		abbrev: "TRIBAL",
		agency: "tribal",
		total_acres : 24098.61,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.0eyx2yb9",
		visible: true,
		layerGroupName: "agency",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#FFFF00'
	},	
	{
		abbrev: "FEDERAL",
		agency: "federal",
		total_acres : 15727892.11,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.2rrltyb9",
		visible: true,
		layerGroupName: "agency",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#C3FDB8'
	},	
	{
		abbrev: "AQ-DFW",
		agency: "Department of Fish and Wildlife",
		total_acres : 1,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.izm5nrk9",
		visible: false,
		layerGroupName: "aquisitions",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#ECC92E'

	},
	{
		abbrev: "AQ-PARKS",
		agency: "Washington Parks Department",
		total_acres : 1,
		total_cost: 1,
		total_revenue: 1,
		mapTarget: "smartmine.yyb3ayvi",
		visible: false,
		layerGroupName: "aquisitions",
		layerGroup: null,
		symbol: '#x21f4;',
		color: '#756BB1'
	},
	{
		abbrev: "AQ-RCO",
		agency: "Recreation and Conservation Office",
		total_acres : 1,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.yyb3ayvi",
		visible: false,
		layerGroupName: "aquisitions",
		layerGroup: null,
		symbol: '#x219a;',
		color: '#229900'
	},
	{
		abbrev: "AQ-DNR",
		agency: "Department of Natural Resources",
		total_acres : 1,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.yyb3ayvi",
		visible: false,
		layerGroupName: "aquisitions",
		layerGroup: null,
		symbol: '#x214a;',
		color: '#347235'
	},
	{
		abbrev: "REVENUE",
		agency: "revenue",
		total_acres : 0,
		total_cost: 0,
		total_revenue: 0,
		mapTarget: "smartmine.izm5nrk9",
		visible: false,
		layerGroupName: "landtypes",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#ECC92E'
	},	
	{
		abbrev: "HABITAT",
		agency: "habitat",
		total_acres : 845671.68,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.u6wxko6r",
		visible: false,
		layerGroupName: "landtypes",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#CC9900'
	},	
	{
		abbrev: "RECREATION",
		agency: "recreation",
		total_acres : 183428.78,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.nxwrvn29",
		visible: false,
		layerGroupName: "landtypes",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#CC00CC'
	},	
	{
		abbrev: "CONSERVATION",
		agency: "conservation",
		total_acres : 159789.33,
		total_cost: 1.00,
		total_revenue: 1.00,
		mapTarget: "smartmine.tpwopqfr",
		visible: false,
		layerGroupName: "landtypes",
		layerGroup: null,
		symbol: '#x2190;',
		color: '#00FFFF'
	}
];