_prefs: 
  baselayer: wa_rco_public_lands_federal
  saveCenter: true
_properties: {}
attribution: Washington RCO Public Lands 2014
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -120.82420349121094
  - 48.61157590482239
  - 10
description: Washington State Federal Public Lands
format: "png8:m=h"
interactivity_layer: test
layers: null
maxzoom: 14
minzoom: 7
name: Washington State Federal Public Lands
source: "mapbox:///smartmine.8d1gu8fr"
styles: 
  - style.mss
template: |-
  <div style="text-align:center;">
  <strong>{{gisacres}}</strong>
  <strong>{{AcquiredDa}}</strong>
  <strong>{{Descriptio }}</strong>
  </div>
